name: FORMAT

on: push

jobs:
    prettier-ts:
        name: Check Prettier of TS and Other Files
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Prettier
              run: npm run format:check

    list-ts:
        name: Check Eslint of TS and Other Files
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Lint
              run: npm run lint:check

    prettier-sol:
        name: Check Prettier of Solidity Files
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Prettier
              run: npm run sol:format:check
    solhint:
        name: Run Solhint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/setup

            - name: Solhint
              run: npm run solhint
    slither:
        name: Run Slither
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.10.0"
            - name: Install Hardhat and dependencies
              run: |
                  npm install
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.10.12"
            - name: Install Slither
              run: |
                  python -m pip install --upgrade pip
                  pip install slither-analyzer
            - name: Compile contracts with Hardhat
              run: |
                  npx hardhat compile
            - name: Run Slither with detailed logging
              run: |
                  slither . > slither-output.txt 2> slither-errors.txt || true
              if: always()
            - name: Upload Slither logs for inspection
              uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: slither-logs
                  paths:
                      - slither-output.txt
                      - slither-errors.txt
